AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - tree-sitter-parsers/**/*
    - tmp/**/*
    - pkg/**/*
    - examples/**/*
    - vendor/**/*

# This should probably be updated
Gemspec/RequireMFA:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/UnusedMethodArgument:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - test/**/*
    - Rakefile

Lint/InheritException:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 29
  Exclude:
    - test/**/*

Metrics/PerceivedComplexity:
  Max: 20

# To please sorbet.
Naming/BlockForwarding:
  Exclude:
    - lib/tree_stand.rb
    - lib/tree_stand/**/*

Security/Eval:
  Exclude:
    - bin/*

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AccessorGrouping:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/tree_sitter/extconf.rb

# To please sorbet.
Style/HashSyntax:
  Exclude:
    - lib/tree_stand.rb
    - lib/tree_stand/**/*

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineBlockChain:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# `unless` is cool and all, but I'd rather not. Less confusion.
Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false
