name: Sync with tree-sitter new releases

on:
  push:
#   schedule:
#     - cron: "23 1 * * *"

jobs:
  check_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get the previous release tag from local project
        id: get_previous_release
        run: |
          PREVIOUS_RELEASE=$(ruby -r ./lib/tree_sitter/version.rb -e 'puts TreeSitter::TREESITTER_VERSION')
          echo "::set-output name=previous_release::$PREVIOUS_RELEASE"

      - name: Get the latest release tag from the external repo
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/tree-sitter/tree-sitter/releases/latest | jq -r .tag_name | sed 's/^v//')
          echo "::set-output name=latest_release::$LATEST_RELEASE"

      - name: Compare release versions
        id: check_versions
        run: |
          if [ "${{ steps.get_previous_release.outputs.previous_release }}" != "${{ steps.get_latest_release.outputs.latest_release }}" ]; then
            echo "New release found"
            echo "::set-output name=version_changed::true"
          else
            echo "No new release"
            echo "::set-output name=version_changed::false"
          fi

      - name: Update version if changed
        if: steps.check_versions.outputs.version_changed == 'true'
        run: |
          sed -i "s/^\([[:space:]]*\)TREESITTER_VERSION = '.*'/\1TREESITTER_VERSION = '${{ steps.get_latest_release.outputs.latest_release }}'/"  lib/tree_sitter/version.rb

      - name: Create pull request
        if: steps.check_versions.outputs.version_changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "tree-sitter: bump to ${{ steps.get_latest_release.outputs.latest_release }}"
          committer: github-actions[bot] <github-actions[bot]@github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: tree-sitter-bump-to-${{ steps.get_latest_release.outputs.latest_release }}
          delete-branch: true
          title: "Bump tree-sitter to ${{ steps.get_latest_release.outputs.latest_release }}"
          draft: false
