name: ci

on: [push, pull_request]

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2]
        os: [macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: build and install tree-sitter
        run: |
          git clone https://github.com/tree-sitter/tree-sitter
          cd tree-sitter
          make
          sudo make install
      - name: ldconfig
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo ldconfig -v
      - name: bundle install
        run: |
          bundle install
      - name: compile
        run: |
          bundle exec rake compile
      - name: test
        run: |
          bundle exec rake test

  Package:
    name: 'Package gems for release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: bundle install
        run: |
          bundle install
      - name: Package install-only gem
        run: |
          bundle exec rake gem
      - name: Package for aarch64-linux
        run: |
          bundle exec rake gem:aarch64-linux
      - name: Package for x86-linux
        run: |
          bundle exec rake gem:x86-linux
      - name: Package for x86_64-linux
        run: |
          bundle exec rake gem:x86_64-linux
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}
          draft: true
          files: |
            ./pkg/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

